### ISSUE TITLE
LDFLAGS when BLAS=1

### ISSUE THREAD

**Issue by thilinarmtb** [gslib/gslib#14]
Hi Stefan,

Currently, if the user set BLAS=1, he has to set LDFLAGS="-lcblas" as well to make
sure the inking process is successful. Shall we edit the `Makefile` so that we do this
on our end? simply adding "-lcblas" to LDFLAGS variable?

**Comment by stgeke** [comment]
I don't think so. The user might want to link against his favorite CBLAS implementation e.g. Intel MKL. Makes sense?

**Comment by thilinarmtb** [comment]
Yes, I agree.
