### ISSUE TITLE
Compiling error for non-blocking allreduce on Blue Gene/Q

### ISSUE THREAD

**Issue by nicooff** [gslib/gslib#24]
Hi,

The non-blocking allreduce function `MPI_Iallreduce` belongs to the MPI-3 standard, which is not supported on Blue Gene/Q (and possibly other machines), thus causing a compilation error for gslib version 1.0.3. Is there a workaround?

Nicolas

**Comment by stgeke** [comment]
Not for now. Note 1.0.3 is a prerelease and there are several things we need to work out.

On 23 Aug 2018, at 21:18, Nicolas <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi,

The non-blocking allreduce function MPI_Iallreduce belongs to the MPI-3 standard, which is not supported on Blue Gene/Q (and possibly other machines), thus causing a compilation error for gslib version 1.0.3. Is there a workaround?

Nicolas

**Comment by nicooff** [comment]
Ok. I just noticed because I was trying to use that version on a BG/Q machine.
